// Movie flags
type 	0
flags 	263237

// Scene files
addScene {	scene	cinemas/demo06/demo06_1.dsk
			}

addScene {	scene	cinemas/demo06/demo06_2.dsk
			}

// Actor files
addActor {	shape	pikis/nv3Model.mod
			bundle	cinemas/demo06/demo06.anm
			anims	cinemas/demo06/demo06.bin
			}

// Scene cuts
addCut {	cut		0	0	360
			flags	3
			actor	pikis/nv3Model.mod
			acflags	3
			anim	2	0
			keys	2	{	
					1	2	5	0
					1	2	4	220
						}
			}

